

teams:
  GREEN_WOOL:
    display_name: "Greens" # team name
    colour: GREEN # team display colour
  YELLOW_WOOL:
    display_name: "Yellows"
    colour: YELLOW
  RED_WOOL:
    display_name: "Reds"
    colour: RED
  BLUE_WOOL:
    display_name: "Blues"
    colour: BLUE

unclaimed-colour: GRAY
unclaimed-material: LIGHT_GRAY

contested-claims:
  # set to -1 to disable timeout contesting
  timeout: 6000 # in ticks (20 / s)
  # in the case multiple teams attack another teams wool, the defending team's colour is entirely replaced on the cube, but
  # there is a contest on who claims the wool, enabling this behaviour will set the wool to unclaimed after the timeout
  # set to false to have it change wool state to an under attack state (except that the dominant team is the new
  # 'current claimer' and everyone else is an attacker.
  #
  # default: true
  revert-multi-claims-to-unclaimed: true

# spawns an end gateway
wool-reveal:
  enabled: true
  on:
    CUBE_ATTACK: # Claimed(team1,_) -> UnderAttack(team1, [team2,...])
      to: ALL # ALL, ATTACKERS, DEFENDERS, PARTIES (attackers + defenders)
      repeat-for-new-teams: true # fire again when another team comes in.
    CUBE_INITIAL_CLAIM: # Unclaimed -> Claimed(_,_)
      to: ALL
    CUBE_DEFEND: # UnderAttack(team1, [team2,...]) -> Claimed(team1,_)
      to: PARTIES
  gateway-duration: 40 # ticks
  gateway-interval: 2000

scrambler:
